### ISSUE TITLE
button datatable cant load all data 

### ISSUE THREAD

**Issue by ovieinten** [bitstudio-id/BITDataTable#2]
pada saat menggunakan button datatable seperti utk export data, data yg terambil hanya dibagian show data yang ditampilkan (next nya atau kolom di data lainnya tidak)

**Comment by iamutaki** [comment]
kalo emng ingin menampilkan keseluruhan, mungkin bisa di pilih all pada saat proses index.

tapi jika ingin customisasi, ketika di index hanya muncul 10 data, ketika ingin di export ingin memampilkan seluruh data, saya lebih sarankan pisah proses nya aja, karena akan mempengaruhi waktu proses render di datatablenya
