### ISSUE TITLE
Index dan getdata tidak berbeda hasil

### ISSUE THREAD

**Issue by ovieinten** [bitstudio-id/BITDataTable#5]
![image](https://user-images.githubusercontent.com/34908193/63069758-6d0fa780-bf42-11e9-8d03-a574b7032d6a.png)
![image](https://user-images.githubusercontent.com/34908193/63069774-7e58b400-bf42-11e9-97e2-91bb1861d59a.png)

**Comment by iamutaki** [comment]
@ovieinten vi ini versi yang lama karne belom di handling error nye, cobe kau tambahkan manual di file BITDataTable nye

**Comment by iamutaki** [comment]
@ovieinten kalo yg di repo, kayak ny udah di handle, cuman di lokal punye kau yg belom tuh vi
